icbc:
  drvrLastName: "YourLastName"
  licenceNumber: "YourLicenceNumber"
  keyword: "YourKeyword"
  expactAfterDate: "2024-05-01"
  expactBeforeDate: "2024-06-01"
  expactAfterTime: "08:00"
  expactBeforeTime: "17:00"
  examClass: "5"

headers:
  Content-type: "application/json"
  User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
  Sec-Ch-Ua-Platform: "macOS"
  Sec-Ch-Ua: '"Chromium";v="124", "Microsoft Edge";v="124", "Not-A.Brand";v="99"'
  Dnt: "1"

email:
  smtp_server: "smtp.your-email-provider.com"
  smtp_port: 587
  sender_address: "your_email@provider.com"
  sender_pass: "your_password"
  receiver_addresses:
    - "receiver1_email@provider.com"
    - "receiver2_email@provider.com"
